name: Blank Issue
description: "If you're 100% sure that you do not need one of the other issue templates, use this one instead."
body:
- type: checkboxes
  attributes:
    label: Information
    options:
    - label: "None of the other issue templates apply"
      required: true
- type: textarea
  attributes:
    label: Description
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
