name: Blank Issue
description: "If you're 100% sure that you do not need one of the other issue templates, use this one instead."
body:
- type: checkboxes
  attributes:
    options:
    - label: "I'm sure that I do not need one of the other issue templates"
      required: true
- type: textarea
  attributes:
    label: Description
  validations:
    required: false
