name: Build Binaries

on:
  workflow_call:
    inputs:
      qmk_ref:
        description: 'qmk_firmware branch to build against'
        default: 'master'
        required: false
        type: string
      keymap_name:
        description: 'keymap name to build with'
        default: ${{ github.actor }}
        required: false
        type: string

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    if: always() && !cancelled()
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        if: always() && !cancelled()
        uses: actions/download-artifact@v3

      - name: Generate Release
        uses: softprops/action-gh-release@v1
        if: always() && !cancelled()
        with:
          token: ${{ github.token }}
          name: Latest QMK Firmware on ${{ github.ref_name }} for ${{ inputs.keymap_name }}
          tag_name: latest_${{ github.ref_name }}_${{ inputs.keymap_name }}
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
          files: |
            **/*.hex
            **/*.bin
            **/*.uf2
